import { Plugin } from '../types';

export const helpPlugin: Plugin = {
  name: 'help',
  description: '显示帮助信息',
  handler: (ctx) => {
    if (ctx.command === 'help') {
      const helpText = [
        '玩机器 命令列表',
        '',
        '对话:',
        '  /ai <内容> - 直接对话',
        '  私聊我 - 直接进入独立私聊上下文',
        '  /voice <内容> - 语音回复',
        '  /tts <内容> - 同上',
        '  /search <关键词> - 联网搜索',
        '  @我 <内容> - @触发',
        '  /reset - 清除记忆',
        '  /presets - 预设列表',
        '  /preset <名> - 切换人格',
        '',
        '玩机器风格:',
        '  /quote [关键词] - 查语录/口癖',
        '  /player <名字> - 查选手倾向',
        '  /team <队伍> - 查队伍倾向',
        '  /gift <礼物名> - 礼物拟态模板',
        '  /cs2news - 实时CS新闻',
        '  /cs2live - CS2直播查询',
        '  /match - 当前比赛',
        '  /ranking - HLTV排名',
        '  /csmood - 玩机器今日心情',
        '  /forecast - 综合每日运势',
        '',
        '每日CS:',
        '  /csplayer - 每日CS选手',
        '  /csteam /csmap /csweapon /csrole - 队伍/地图/武器/定位',
        '  /csutility /cstactic /csclutch - 道具/战术/残局',
        '  /csloadout - 每日CS全套',
        '',
        '趣味:',
        '  /roll [N|NdM] - 骰子',
        '  /luck - 运势',
        '  /jrrp - 今日人品',
        '  /choose A,B,C - 帮选',
        '  /rand [min] [max] - 随机数',
        '',
        '工具:',
        '  /ping - 在线',
        '  /whoami - 查bot号/群号',
        '  /status - 运行状态',
        '  /diag - 严格自检',
        '  /mem - 内存状态',
        '  /time - 时间',
        '  /stats - 群统计',
        '  /me - 我在群的活跃度',
        '  /trace last - 最近回复trace',
        '  /vision status / test - 识图诊断',
        '  /voice status / test / stt / clean - 语音诊断',
        '  /voice clone [URL] - 安装克隆样本',
        '',
        '知识库:',
        '  /kb search <关键词> - 检索',
        '  /kb stats - 状态',
        '  /kb refresh - 联网刷新',
        '  /kb audit - 审计',
        '  /kb auto on|off|run - 自动更新',
        '',
        '管理(仅admin):',
        '  /reload - 重载配置',
        '  /maint status|login|config|clean - 维护面板',
        '  /gc - 强制GC',
        '  /ban /unban /kick /title',
        '  /kb preview / ingest / list / show / commit / drop',
        '',
        '其他:',
        '  戳一戳我 - 玩机器风格回应',
        '  复读2次我会跟',
        '  CS2/玩机器相关话题会主动接',
        '  支持emoji 包括 😂🤣',
      ].join('\n');

      ctx.reply(helpText);
      return true;
    }
    return false;
  },
};
