import { Plugin } from '../types';
import { detectFuzzyCommand } from './fuzzy-command';

export const helpPlugin: Plugin = {
  name: 'help',
  description: '显示帮助信息',
  handler: (ctx) => {
    const fuzzy = ctx.command ? null : detectFuzzyCommand(ctx.rawText.trim());
    if (ctx.command === 'help' || fuzzy === 'help') {
      const helpText = [
        '玩机器 命令列表',
        '',
        '对话:',
        '  /ai <内容> - 直接对话',
        '  私聊我 - 直接进入独立私聊上下文',
        '  /voice <内容> - 语音回复',
        '  /tts <内容> - 同上',
        '  /search <关键词> - 联网搜索',
        '  @我 <内容> - @触发',
        '  /reset - 清除记忆',
        '  /presets - 预设列表',
        '  /preset <名> - 切换人格',
        '',
        '玩机器风格:',
        '  /quote [关键词] - 查语录/口癖',
        '  /scene [场景词] - 抽直播场景模板，适合白给/礼物/残局/切片语感',
        '  /player <名字> - 查选手倾向；带“最新/现在/状态”会读CS API统计',
        '  /team <队伍> - 查队伍倾向；带“最新/阵容/排名”会读CS API阵容/VRS',
        '  /gift <礼物名> - 礼物拟态模板',
        '  /cs2news - 实时CS新闻',
        '  /csbrief - 今日CS短报(比赛/赛果/排名)',
        '  /cs2live - CS2直播查询',
        '  /match - 当前比赛',
        '  /ranking - VRS/HLTV镜像排名',
        '  /csmood - 玩机器今日心情',
        '  /forecast - 综合每日运势',
        '',
        '每日CS:',
        '  /csplayer - 每日CS选手',
        '  /csteam /csmap /csweapon /csrole - 队伍/地图/武器/定位，全部带图',
        '  /csutility /cstactic /csclutch - 道具/战术/残局',
        '  /csloadout - 每日CS全套',
        '  /csimage test all - 测每日CS真实图源',
        '  /csplayer status - 看图片缓存/限流/兜底状态',
        '  也可以直接说: 今日CS / 今天抽个选手 / 今日地图 / 今天用什么枪',
        '',
        '趣味:',
        '  /roll [N|NdM] - 骰子',
        '  /luck - 运势',
        '  /jrrp - 今日人品',
        '  /choose A,B,C - 帮选',
        '  /rand [min] [max] - 随机数',
        '',
        '工具:',
        '  /ping - 在线',
        '  /whoami - 查bot号/群号',
        '  /status - 运行状态',
        '  /diag - 严格自检',
        '  /data - 实时数据健康度(测CS API/Liquipedia/webSearch)',
        '  /mem - 内存/上下文/RAG状态，/mem search <关键词>',
        '  /mem recent [条数] - 看最近上下文和RAG索引',
        '  /time - 时间',
        '  /stats - 群统计',
        '  /me - 我在群的活跃度',
        '  /trace last - 最近回复trace',
        '  /vision status / test - 识图诊断',
        '  /voice status / test / stt / clean - 语音诊断',
        '  /voice clone [URL] - 安装克隆样本',
        '  发图后说“帮我看图/识图/看看这张图” - 直接识图',
        '',
        '知识库:',
        '  /kb search <关键词> - 检索',
        '  /kb stats - 状态',
        '  /kb refresh - 联网刷新',
        '  /kb audit - 审计',
        '  /kb auto on|off|run - 自动更新',
        '',
        '管理(仅admin):',
        '  /reload - 重载配置',
        '  /tune <项> <值> - 快速调参(trigger/related/tts/poke/temp/maxtokens/minchars/cooldown)',
        '  /maint status|login|config|clean - 维护面板',
        '  /gc - 强制GC',
        '  /csprewarm - 预下载所有选手图(慢，受限流影响)',
        '  /ban /unban /kick /title',
        '  /kb preview / ingest / list / show / commit / drop',
        '',
        '其他:',
        '  戳一戳我 - 玩机器风格回应',
        '  复读2次我会跟',
        '  CS2/玩机器相关话题会主动接',
        '  支持emoji，会把常见emoji转QQ经典表情并限制刷屏',
        '',
        '🎭 表情和贴纸:',
        '  /stickers - 查可用 QQ 表情和本地贴纸',
        '  /face <名字或id> - 发 QQ 经典表情(如/face 呲牙)',
        '  /sticker <名字> - 发本地贴纸',
        '  AI 对话会在合适语境用[呲牙][笑哭][思考]等标签自动转表情',
        '',
        '🔥 中文模糊触发 (不需要 / 前缀，自然语言)：',
        '  我多活跃 / 看看我 / 我的活跃度 → /me',
        '  群统计 / 话痨排行 → /stats',
        '  今天有什么比赛 / 现在打谁 → /match',
        '  hltv排名 / vrs排名 / 现在第一是谁 → /ranking',
        '  最近战报 / 昨天比赛结果 → /cs2news',
        '  cs短报 / cs日报 / 今天cs看点 → /csbrief',
        '  直播场景 / 白给场景 / 礼物话术 → /scene',
        '  cs直播 / 玩机器开播了吗 → /cs2live',
        '  玩机器今天什么状态 → /csmood',
        '  今日运势 → /forecast',
        '  今日CS / 今日选手 / 今日队伍 / 今日地图 / 今日武器 / 今日残局 → 每日CS系列',
        '  语音说 XXX / 直接念 XXX / 朗读 XXX → 直接生成语音',
        '  帮我看图 / 看看这张图 → 识图',
        '  学一下我的声音 → /voice clone',
        '  内存状态 → /mem',
        '  帮助 / 怎么用 / 功能列表 → /help',
      ].join('\n');

      ctx.reply(helpText);
      return true;
    }
    return false;
  },
};
